Homework #2 is completed
Syzygy9/EvgeniyaKazakevich pull request #2
Opened 2020-04-08 21:08 UTC by Syzygy9

Please check Homework#2

2020-04-11 22:19 UTC, DmitryKhodakovsky requested changes
Please resolve comments ASAP. Tests does not work though the command `mvn clean test -P hw2-all-tests`

2020-04-11 22:19 UTC, DmitryKhodakovsky commented on src/test/java/hw2/PreAssertionClass.java
> +public class PreAssertionClass {
Why do you decide choose this strange name for the class?

2020-04-11 22:19 UTC, DmitryKhodakovsky commented on src/test/java/hw2/ex2/AssertElementsTest.java
> +        assertTrue(elementYellow.isDisplayed(), "Dropdown selected color is not displayed in log row");
Why do you put full log text into locator? Please try to find appropriate locator

2020-04-11 22:19 UTC, DmitryKhodakovsky commented on src/test/resources/suites/hw2/AllTests.xml
> +<suite name="All the tests suite">
This suite does not work

2020-04-11 22:19 UTC, DmitryKhodakovsky commented on src/test/resources/suites/hw2/Exercise1.xml
> +<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
This suite does not work

2020-04-11 22:19 UTC, DmitryKhodakovsky commented on src/test/resources/suites/hw2/Exercise2.xml
> +<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
This suite does not work

2020-04-12 09:48 UTC, Syzygy9 commented
I have made the corrections. Please check.

2020-04-14 09:40 UTC, DmitryKhodakovsky commented on src/test/java/hw2/ex2/AssertElementsTest.java
> +        assertTrue(elementYellow.isDisplayed(), "Dropdown selected color is not displayed in log row");
Why do you ignore my comments?

2020-04-14 09:40 UTC, DmitryKhodakovsky approved these changes
HW2 is accepted with comment,. could be merged to the master branch

2020-04-14 18:17 UTC, merged